### ISSUE TITLE
Make Skyfield, Astronomy optional

### ISSUE THREAD

**Issue by jrd** [workalendar/workalendar#660]
`astronomy` module might interest some people I’m sure, but the `skyfield` dependency will pull `numpy` which is huge (and maybe complex to build on some environment).

So is it possible to have a `workalendar` package with a `[astronomy]` extra that will pull `skyfield` and `skyfield-data`?
That way, people who also needs the `astronomy` module will request `workalendar[astronomy]` and others just `workalendar`.

This is, of course, if it’s possible.
What do you think?

**Comment by ewjoachim** [comment]
One other possible solution could be to have a different package (in the same codebase) that uses those libs to generates the astronomical information and that we can run once a year or once a release with everything, and have workalendar use these information but not require the libs themselves.

**Comment by jrd** [comment]
Yes that seems to be a good idea.

**Comment by ewjoachim** [comment]
(Would that be compatible with our dependencies' licences ? I think so but I don't know)

**Comment by jrd** [comment]
How can I help getting this done?

**Comment by ewjoachim** [comment]
I would have like to get an opinion from @brunobord before spending time on this. He's the maintainer and he's the architect for this lib :)

If he says :+1: then I believe you can start working on a PR.
What needs to be done is to create an intermediary format, easily writtable on disk (I'd say JSON) that lets you calculate all the working/non-working days that depends on astronomy elements without actually calling the astronomy-related libs (so maybe this will be for example a list of all relevant calculation results for the 100 next years). This probably means the first thing to do is audit the entire lib and find how the astronomy-related libs are called.

Then once this is done, we need a script that will generate those JSON files, and we'll need a bit of "packaging magic" so that it's easy to run the script with the astronomy libs, and we can safely remove them from the runtime workalendar (`extras_require` could be a lead, but I'd prefer if we could remove those entirely from the lib. That being said, may a simple file `requirements.astronomy.txt` would suffice).

Does this make sense ?

**Comment by brunobord** [comment]
Made a 16.0.0rc1 release ; will have to make a few tests tomorrow, we're getting closer.

**Comment by brunobord** [comment]
The latest release (16.0.0) includes your tremendous work. Thank you a million for your time and your patience. You rock!

* https://pypi.org/project/workalendar/16.0.0/
* https://github.com/workalendar/workalendar/releases/tag/16.0.0

Happy upgrading!
